[pytest]
addopts = --import-mode=importlib
testpaths = anonymization docker orchestrator ap18
python_files = test_*.py AP18_test_*.py
norecursedirs = test_akte plain_test .git node_modules cases venv
pythonpath = anonymization docker/litellm orchestrator ap18
