[pytest]
addopts = --import-mode=importlib
testpaths = anonymization docker orchestrator
norecursedirs = test_akte plain_test .git node_modules cases venv
pythonpath = anonymization docker/litellm orchestrator
